"""criacao_tabelas

Revision ID: 89674e4f3b9d
Revises: 
Create Date: 2026-04-28 12:19:56.338545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89674e4f3b9d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('data_nascimento', sa.DateTime(), nullable=False),
    sa.Column('rg', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('ATIVO', 'INATIVO', name='statuspaciente'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_deleted_at'), 'pacientes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_pacientes_id'), 'pacientes', ['id'], unique=False)
    op.create_index(op.f('ix_pacientes_nome'), 'pacientes', ['nome'], unique=False)
    op.create_table('responsaveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_responsaveis_deleted_at'), 'responsaveis', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_responsaveis_id'), 'responsaveis', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.Enum('ADMIN', 'GESTOR', 'TERAPEUTA', name='tipousuario'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_deleted_at'), 'usuarios', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('RG', 'COMPROVANTE_RESIDENCIA', 'LAUDO_MEDICO', 'RECEITA_MEDICA', 'ANAMNESE', name='tipodocumento'), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_deleted_at'), 'documentos', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_documentos_id'), 'documentos', ['id'], unique=False)
    op.create_table('paciente_responsavel',
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['responsaveis.id'], ),
    sa.PrimaryKeyConstraint('paciente_id', 'responsavel_id')
    )
    op.create_table('terapeutas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('especialidade', sa.String(length=100), nullable=False),
    sa.Column('carga_horaria_semanal', sa.Integer(), nullable=False),
    sa.Column('limite_atendimentos', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_terapeutas_deleted_at'), 'terapeutas', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_terapeutas_id'), 'terapeutas', ['id'], unique=False)
    op.create_table('agendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('terapeuta_id', sa.Integer(), nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('AGENDADO', 'PRESENTE', 'FALTOU', 'CANCELADO', name='statusagenda'), nullable=False),
    sa.Column('motivo_cancelamento', sa.Text(), nullable=True),
    sa.Column('agendamento_original_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['agendamento_original_id'], ['agendas.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['terapeuta_id'], ['terapeutas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendas_data_hora_inicio'), 'agendas', ['data_hora_inicio'], unique=False)
    op.create_index(op.f('ix_agendas_deleted_at'), 'agendas', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_agendas_id'), 'agendas', ['id'], unique=False)
    op.create_table('paciente_terapeuta',
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('terapeuta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['terapeuta_id'], ['terapeutas.id'], ),
    sa.PrimaryKeyConstraint('paciente_id', 'terapeuta_id')
    )
    op.create_table('atendimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agenda_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['agenda_id'], ['agendas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agenda_id')
    )
    op.create_index(op.f('ix_atendimentos_deleted_at'), 'atendimentos', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_atendimentos_id'), 'atendimentos', ['id'], unique=False)
    op.create_table('evolucoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('inativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('updated_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atendimento_id')
    )
    op.create_index(op.f('ix_evolucoes_deleted_at'), 'evolucoes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_evolucoes_id'), 'evolucoes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evolucoes_id'), table_name='evolucoes')
    op.drop_index(op.f('ix_evolucoes_deleted_at'), table_name='evolucoes')
    op.drop_table('evolucoes')
    op.drop_index(op.f('ix_atendimentos_id'), table_name='atendimentos')
    op.drop_index(op.f('ix_atendimentos_deleted_at'), table_name='atendimentos')
    op.drop_table('atendimentos')
    op.drop_table('paciente_terapeuta')
    op.drop_index(op.f('ix_agendas_id'), table_name='agendas')
    op.drop_index(op.f('ix_agendas_deleted_at'), table_name='agendas')
    op.drop_index(op.f('ix_agendas_data_hora_inicio'), table_name='agendas')
    op.drop_table('agendas')
    op.drop_index(op.f('ix_terapeutas_id'), table_name='terapeutas')
    op.drop_index(op.f('ix_terapeutas_deleted_at'), table_name='terapeutas')
    op.drop_table('terapeutas')
    op.drop_table('paciente_responsavel')
    op.drop_index(op.f('ix_documentos_id'), table_name='documentos')
    op.drop_index(op.f('ix_documentos_deleted_at'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_deleted_at'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_responsaveis_id'), table_name='responsaveis')
    op.drop_index(op.f('ix_responsaveis_deleted_at'), table_name='responsaveis')
    op.drop_table('responsaveis')
    op.drop_index(op.f('ix_pacientes_nome'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_id'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_deleted_at'), table_name='pacientes')
    op.drop_table('pacientes')
    # ### end Alembic commands ###
